name: Lint, Build & Test

on:
  push:
    branches: [$default-branch, main]
  pull_request:
    branches: [$default-branch, main]
  
jobs:
  lint-build-test:
    name: Lint, Build & Tests
    runs-on: ubuntu-latests
    steps:
      - name: Check out
        uses: actions/checkout@v3
      - name: Install foundry
        run: |
          curl -L https://foundry.paradigm.xyz | bash && \
          eval "$(sed -n '/foundry/p' ~/.bashrc)" && \
          echo $PATH | tee -a $GITHUB_PATH
      - name: Install chain tools
        run: | node
          foundryup
      - name: Yarn install
        run: | node
          yarn install --immutable
      - name: Build
        run: |
          yarn build
      - name: Test
        run: | node
          yarn tests
  
